version: '3'

services:
  ws2-nginx:
    build:
      context: ./docker/nginx
    container_name: nginx-ws2
    depends_on:
      - ws2-php
    environment:
      - WWWUSER:${UID:-1000}
      - WWWGROUP:${GID:-1000}
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./public:/www/public

  ws2-php:
    build:
      context: ./docker/php82
    container_name: php82-ws2
    depends_on:
      - ws2-mariadb
    volumes:
      - .:/www

  ws2-mariadb:
    build:
      context: ./docker/mariadb
    container_name: mariadb-ws2
    environment:
    - MYSQL_ROOT_PASSWORD=ws2
    - MYSQL_DATABASE=ws2
    - MYSQL_USER=ws2
    - MYSQL_PASSWORD=ws2
    - MYSQL_ROOT_HOST=%
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./docker/volumes/mariadb:/var/lib/mysql